#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 noet
#
# Wrapper script for 'install'.

# This file is part of GnuPG for OS X.
#
# GnuPG for OS X is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GnuPG for OS X is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuPG for OS X. If not, see https://www.gnu.org/licenses/ .

i=$#
j=0
while [ ${i} -ge 0 ]; do
	# DISTDIR and INSTALLDIR will be replaced by "build.sh".
	args[${j}]=$(echo ${BASH_ARGV[$i]} | sed -e 's,INSTALLDIR,DISTDIR,g')
	i=$((i - 1))
	j=$((j + 1))
done

set -x
mkdir -p "${args[$#]}"
install ${args[*]} || true
