#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 noet
#
# Wrapper script for 'install-sh'.

# This file is part of GnuPG for OS X.
#
# GnuPG for OS X is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GnuPG for OS X is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuPG for OS X. If not, see https://www.gnu.org/licenses/ .

set -x

# DISTDIR and INSTALLDIR will be replaced by "build.sh".
# shellcheck disable=2001,2046
"${0%-wrapper}.orig" $(echo "$@" | sed -e 's,INSTALLDIR,DISTDIR,g')
exit $?
